import React from 'react';
import { PropsWithChildren } from 'react';
import { cookies } from 'next/headers';
import Link from 'next/link';
import { css } from '@ui/css';
import { getTheme, ThemeName } from '@ui/themes';
import './globals.css';
import Providers from '@/app/providers/Providers';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default async function RootLayout({ children }: PropsWithChildren) {
  const store = cookies();
  const themeName = store.get('theme')?.value as ThemeName;
  const theme = themeName && (await getTheme(themeName));

  const TestDiv = css({
    color: 'text',
    backgroundColor: 'background',
  });

  return (
    <html lang="ko" data-panda-theme={themeName}>
      {themeName && (
        <head>{<style type="text/css" id={theme.id} dangerouslySetInnerHTML={{ __html: theme.css }} />}</head>
      )}
      <body>
        <header>
          <ul>
            <li>
              <Link href="/">Home</Link>
            </li>
            <li>
              <Link href="/account">account</Link>
            </li>
          </ul>
        </header>
        <Providers>{children}</Providers>
        <div className={TestDiv}>테마 테스트!</div>
      </body>
    </html>
  );
}
